//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSCS.WinApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\DayEnd.log")]
        public string filePath {
            get {
                return ((string)(this["filePath"]));
            }
            set {
                this["filePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string searchText {
            get {
                return ((string)(this["searchText"]));
            }
            set {
                this["searchText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>136             </string>\r\n  <string>140             </string>\r\n  <string>" +
            "144             </string>\r\n  <string>167             </string>\r\n  <string>178   " +
            "          </string>\r\n  <string>181             </string>\r\n  <string>193         " +
            "    </string>\r\n  <string>216             </string>\r\n  <string>222             </" +
            "string>\r\n  <string>223             </string>\r\n  <string>416             </string" +
            ">\r\n  <string>421             </string>\r\n  <string>449             </string>\r\n  <" +
            "string>458             </string>\r\n  <string>473             </string>\r\n  <string" +
            ">478             </string>\r\n  <string>490             </string>\r\n  <string>507  " +
            "           </string>\r\n  <string>519             </string>\r\n  <string>520        " +
            "     </string>\r\n  <string>534             </string>\r\n  <string>535             <" +
            "/string>\r\n  <string>547             </string>\r\n  <string>581             </strin" +
            "g>\r\n  <string>582             </string>\r\n  <string>594             </string>\r\n  " +
            "<string>595             </string>\r\n  <string>644             </string>\r\n  <strin" +
            "g>667             </string>\r\n  <string>668             </string>\r\n  <string>677 " +
            "            </string>\r\n  <string>678             </string>\r\n  <string>683       " +
            "      </string>\r\n  <string>691             </string>\r\n  <string>707             " +
            "</string>\r\n  <string>754             </string>\r\n  <string>757             </stri" +
            "ng>\r\n  <string>794             </string>\r\n  <string>798             </string>\r\n " +
            " <string>826             </string>\r\n  <string>853             </string>\r\n  <stri" +
            "ng>854             </string>\r\n  <string>855             </string>\r\n  <string>866" +
            "             </string>\r\n  <string>870             </string>\r\n  <string>877      " +
            "       </string>\r\n  <string>880             </string>\r\n  <string>887            " +
            " </string>\r\n  <string>922             </string>\r\n  <string>928             </str" +
            "ing>\r\n  <string>929             </string>\r\n  <string>936             </string>\r\n" +
            "  <string>937             </string>\r\n  <string>956             </string>\r\n  <str" +
            "ing>957             </string>\r\n  <string>971             </string>\r\n  <string>97" +
            "3             </string>\r\n  <string>987             </string>\r\n  <string>989     " +
            "        </string>\r\n  <string>999             </string>\r\n  <string>128           " +
            "  </string>\r\n  <string>137             </string>\r\n  <string>141             </st" +
            "ring>\r\n  <string>147             </string>\r\n  <string>192             </string>\r" +
            "\n  <string>217             </string>\r\n  <string>225             </string>\r\n  <st" +
            "ring>274             </string>\r\n  <string>278             </string>\r\n  <string>2" +
            "87             </string>\r\n  <string>289             </string>\r\n  <string>387    " +
            "         </string>\r\n  <string>417             </string>\r\n  <string>436          " +
            "   </string>\r\n  <string>439             </string>\r\n  <string>452             </s" +
            "tring>\r\n  <string>465             </string>\r\n  <string>472             </string>" +
            "\r\n  <string>491             </string>\r\n  <string>493             </string>\r\n  <s" +
            "tring>494             </string>\r\n  <string>496             </string>\r\n  <string>" +
            "502             </string>\r\n  <string>560             </string>\r\n  <string>563   " +
            "          </string>\r\n  <string>566             </string>\r\n  <string>568         " +
            "    </string>\r\n  <string>569             </string>\r\n  <string>570             </" +
            "string>\r\n  <string>571             </string>\r\n  <string>574             </string" +
            ">\r\n  <string>578             </string>\r\n  <string>579             </string>\r\n  <" +
            "string>587             </string>\r\n  <string>624             </string>\r\n  <string" +
            ">647             </string>\r\n  <string>655             </string>\r\n  <string>682  " +
            "           </string>\r\n  <string>719             </string>\r\n  <string>745        " +
            "     </string>\r\n  <string>776             </string>\r\n  <string>779             <" +
            "/string>\r\n  <string>811             </string>\r\n  <string>827             </strin" +
            "g>\r\n  <string>847             </string>\r\n  <string>852             </string>\r\n  " +
            "<string>867             </string>\r\n  <string>875             </string>\r\n  <strin" +
            "g>883             </string>\r\n  <string>885             </string>\r\n  <string>930 " +
            "            </string>\r\n  <string>939             </string>\r\n  <string>943       " +
            "      </string>\r\n  <string>944             </string>\r\n  <string>948             " +
            "</string>\r\n  <string>950             </string>\r\n  <string>963             </stri" +
            "ng>\r\n  <string>964             </string>\r\n  <string>966             </string>\r\n " +
            " <string>975             </string>\r\n  <string>113             </string>\r\n  <stri" +
            "ng>114             </string>\r\n  <string>127             </string>\r\n  <string>132" +
            "             </string>\r\n  <string>138             </string>\r\n  <string>139      " +
            "       </string>\r\n  <string>142             </string>\r\n  <string>166            " +
            " </string>\r\n  <string>176             </string>\r\n  <string>183             </str" +
            "ing>\r\n  <string>184             </string>\r\n  <string>191             </string>\r\n" +
            "  <string>197             </string>\r\n  <string>228             </string>\r\n  <str" +
            "ing>243             </string>\r\n  <string>250             </string>\r\n  <string>27" +
            "0             </string>\r\n  <string>275             </string>\r\n  <string>282     " +
            "        </string>\r\n  <string>442             </string>\r\n  <string>450           " +
            "  </string>\r\n  <string>456             </string>\r\n  <string>476             </st" +
            "ring>\r\n  <string>479             </string>\r\n  <string>487             </string>\r" +
            "\n  <string>500             </string>\r\n  <string>515             </string>\r\n  <st" +
            "ring>546             </string>\r\n  <string>549             </string>\r\n  <string>5" +
            "67             </string>\r\n  <string>572             </string>\r\n  <string>575    " +
            "         </string>\r\n  <string>580             </string>\r\n  <string>583          " +
            "   </string>\r\n  <string>586             </string>\r\n  <string>589             </s" +
            "tring>\r\n  <string>625             </string>\r\n  <string>639             </string>" +
            "\r\n  <string>653             </string>\r\n  <string>654             </string>\r\n  <s" +
            "tring>666             </string>\r\n  <string>676             </string>\r\n  <string>" +
            "679             </string>\r\n  <string>680             </string>\r\n  <string>687   " +
            "          </string>\r\n  <string>729             </string>\r\n  <string>752         " +
            "    </string>\r\n  <string>758             </string>\r\n  <string>761             </" +
            "string>\r\n  <string>785             </string>\r\n  <string>792             </string" +
            ">\r\n  <string>796             </string>\r\n  <string>812             </string>\r\n  <" +
            "string>851             </string>\r\n  <string>878             </string>\r\n  <string" +
            ">879             </string>\r\n  <string>884             </string>\r\n  <string>888  " +
            "           </string>\r\n  <string>897             </string>\r\n  <string>915        " +
            "     </string>\r\n  <string>923             </string>\r\n  <string>924             <" +
            "/string>\r\n  <string>926             </string>\r\n  <string>934             </strin" +
            "g>\r\n  <string>938             </string>\r\n  <string>940             </string>\r\n  " +
            "<string>949             </string>\r\n  <string>983             </string>\r\n  <strin" +
            "g>993             </string>\r\n  <string>996             </string>\r\n  <string>155 " +
            "            </string>\r\n  <string>160             </string>\r\n  <string>170       " +
            "      </string>\r\n  <string>175             </string>\r\n  <string>198             " +
            "</string>\r\n  <string>199             </string>\r\n  <string>232             </stri" +
            "ng>\r\n  <string>277             </string>\r\n  <string>279             </string>\r\n " +
            " <string>281             </string>\r\n  <string>372             </string>\r\n  <stri" +
            "ng>440             </string>\r\n  <string>446             </string>\r\n  <string>447" +
            "             </string>\r\n  <string>455             </string>\r\n  <string>475      " +
            "       </string>\r\n  <string>484             </string>\r\n  <string>499            " +
            " </string>\r\n  <string>510             </string>\r\n  <string>523             </str" +
            "ing>\r\n  <string>528             </string>\r\n  <string>529             </string>\r\n" +
            "  <string>531             </string>\r\n  <string>545             </string>\r\n  <str" +
            "ing>550             </string>\r\n  <string>564             </string>\r\n  <string>57" +
            "6             </string>\r\n  <string>585             </string>\r\n  <string>591     " +
            "        </string>\r\n  <string>627             </string>\r\n  <string>641           " +
            "  </string>\r\n  <string>660             </string>\r\n  <string>665             </st" +
            "ring>\r\n  <string>670             </string>\r\n  <string>688             </string>\r" +
            "\n  <string>695             </string>\r\n  <string>739             </string>\r\n  <st" +
            "ring>748             </string>\r\n  <string>768             </string>\r\n  <string>7" +
            "82             </string>\r\n  <string>783             </string>\r\n  <string>784    " +
            "         </string>\r\n  <string>786             </string>\r\n  <string>787          " +
            "   </string>\r\n  <string>790             </string>\r\n  <string>795             </s" +
            "tring>\r\n  <string>810             </string>\r\n  <string>822             </string>" +
            "\r\n  <string>831             </string>\r\n  <string>843             </string>\r\n  <s" +
            "tring>845             </string>\r\n  <string>857             </string>\r\n  <string>" +
            "862             </string>\r\n  <string>890             </string>\r\n  <string>891   " +
            "          </string>\r\n  <string>916             </string>\r\n  <string>917         " +
            "    </string>\r\n  <string>925             </string>\r\n  <string>931             </" +
            "string>\r\n  <string>951             </string>\r\n  <string>980             </string" +
            ">\r\n  <string>990             </string>\r\n  <string>995             </string>\r\n  <" +
            "string>133             </string>\r\n  <string>180             </string>\r\n  <string" +
            ">189             </string>\r\n  <string>196             </string>\r\n  <string>226  " +
            "           </string>\r\n  <string>283             </string>\r\n  <string>379        " +
            "     </string>\r\n  <string>437             </string>\r\n  <string>443             <" +
            "/string>\r\n  <string>448             </string>\r\n  <string>464             </strin" +
            "g>\r\n  <string>482             </string>\r\n  <string>486             </string>\r\n  " +
            "<string>489             </string>\r\n  <string>495             </string>\r\n  <strin" +
            "g>521             </string>\r\n  <string>522             </string>\r\n  <string>524 " +
            "            </string>\r\n  <string>525             </string>\r\n  <string>530       " +
            "      </string>\r\n  <string>533             </string>\r\n  <string>537             " +
            "</string>\r\n  <string>590             </string>\r\n  <string>593             </stri" +
            "ng>\r\n  <string>597             </string>\r\n  <string>598             </string>\r\n " +
            " <string>643             </string>\r\n  <string>659             </string>\r\n  <stri" +
            "ng>686             </string>\r\n  <string>690             </string>\r\n  <string>717" +
            "             </string>\r\n  <string>723             </string>\r\n  <string>737      " +
            "       </string>\r\n  <string>746             </string>\r\n  <string>766            " +
            " </string>\r\n  <string>771             </string>\r\n  <string>774             </str" +
            "ing>\r\n  <string>777             </string>\r\n  <string>833             </string>\r\n" +
            "  <string>834             </string>\r\n  <string>835             </string>\r\n  <str" +
            "ing>839             </string>\r\n  <string>841             </string>\r\n  <string>84" +
            "2             </string>\r\n  <string>858             </string>\r\n  <string>893     " +
            "        </string>\r\n  <string>894             </string>\r\n  <string>895           " +
            "  </string>\r\n  <string>913             </string>\r\n  <string>918             </st" +
            "ring>\r\n  <string>919             </string>\r\n  <string>945             </string>\r" +
            "\n  <string>961             </string>\r\n  <string>970             </string>\r\n  <st" +
            "ring>124             </string>\r\n  <string>126             </string>\r\n  <string>1" +
            "43             </string>\r\n  <string>159             </string>\r\n  <string>169    " +
            "         </string>\r\n  <string>179             </string>\r\n  <string>190          " +
            "   </string>\r\n  <string>194             </string>\r\n  <string>195             </s" +
            "tring>\r\n  <string>237             </string>\r\n  <string>239             </string>" +
            "\r\n  <string>269             </string>\r\n  <string>380             </string>\r\n  <s" +
            "tring>454             </string>\r\n  <string>469             </string>\r\n  <string>" +
            "481             </string>\r\n  <string>485             </string>\r\n  <string>492   " +
            "          </string>\r\n  <string>497             </string>\r\n  <string>498         " +
            "    </string>\r\n  <string>518             </string>\r\n  <string>526             </" +
            "string>\r\n  <string>538             </string>\r\n  <string>561             </string" +
            ">\r\n  <string>562             </string>\r\n  <string>573             </string>\r\n  <" +
            "string>577             </string>\r\n  <string>619             </string>\r\n  <string" +
            ">622             </string>\r\n  <string>623             </string>\r\n  <string>669  " +
            "           </string>\r\n  <string>684             </string>\r\n  <string>685        " +
            "     </string>\r\n  <string>699             </string>\r\n  <string>718             <" +
            "/string>\r\n  <string>749             </string>\r\n  <string>753             </strin" +
            "g>\r\n  <string>760             </string>\r\n  <string>765             </string>\r\n  " +
            "<string>769             </string>\r\n  <string>778             </string>\r\n  <strin" +
            "g>781             </string>\r\n  <string>836             </string>\r\n  <string>872 " +
            "            </string>\r\n  <string>881             </string>\r\n  <string>882       " +
            "      </string>\r\n  <string>889             </string>\r\n  <string>896             " +
            "</string>\r\n  <string>911             </string>\r\n  <string>942             </stri" +
            "ng>\r\n  <string>946             </string>\r\n  <string>947             </string>\r\n " +
            " <string>962             </string>\r\n  <string>968             </string>\r\n  <stri" +
            "ng>969             </string>\r\n  <string>974             </string>\r\n  <string>116" +
            "             </string>\r\n  <string>148             </string>\r\n  <string>149      " +
            "       </string>\r\n  <string>156             </string>\r\n  <string>162            " +
            " </string>\r\n  <string>163             </string>\r\n  <string>164             </str" +
            "ing>\r\n  <string>174             </string>\r\n  <string>186             </string>\r\n" +
            "  <string>210             </string>\r\n  <string>227             </string>\r\n  <str" +
            "ing>229             </string>\r\n  <string>336             </string>\r\n  <string>37" +
            "1             </string>\r\n  <string>423             </string>\r\n  <string>466     " +
            "        </string>\r\n  <string>467             </string>\r\n  <string>527           " +
            "  </string>\r\n  <string>532             </string>\r\n  <string>565             </st" +
            "ring>\r\n  <string>584             </string>\r\n  <string>592             </string>\r" +
            "\n  <string>614             </string>\r\n  <string>628             </string>\r\n  <st" +
            "ring>649             </string>\r\n  <string>656             </string>\r\n  <string>6" +
            "57             </string>\r\n  <string>663             </string>\r\n  <string>664    " +
            "         </string>\r\n  <string>672             </string>\r\n  <string>681          " +
            "   </string>\r\n  <string>694             </string>\r\n  <string>696             </s" +
            "tring>\r\n  <string>722             </string>\r\n  <string>726             </string>" +
            "\r\n  <string>743             </string>\r\n  <string>744             </string>\r\n  <s" +
            "tring>747             </string>\r\n  <string>759             </string>\r\n  <string>" +
            "763             </string>\r\n  <string>764             </string>\r\n  <string>767   " +
            "          </string>\r\n  <string>770             </string>\r\n  <string>799         " +
            "    </string>\r\n  <string>817             </string>\r\n  <string>820             </" +
            "string>\r\n  <string>821             </string>\r\n  <string>828             </string" +
            ">\r\n  <string>829             </string>\r\n  <string>832             </string>\r\n  <" +
            "string>837             </string>\r\n  <string>844             </string>\r\n  <string" +
            ">848             </string>\r\n  <string>849             </string>\r\n  <string>850  " +
            "           </string>\r\n  <string>861             </string>\r\n  <string>868        " +
            "     </string>\r\n  <string>869             </string>\r\n  <string>876             <" +
            "/string>\r\n  <string>886             </string>\r\n  <string>892             </strin" +
            "g>\r\n  <string>912             </string>\r\n  <string>933             </string>\r\n  " +
            "<string>941             </string>\r\n  <string>953             </string>\r\n  <strin" +
            "g>954             </string>\r\n  <string>960             </string>\r\n  <string>976 " +
            "            </string>\r\n  <string>977             </string>\r\n  <string>152       " +
            "      </string>\r\n  <string>157             </string>\r\n  <string>161             " +
            "</string>\r\n  <string>165             </string>\r\n  <string>171             </stri" +
            "ng>\r\n  <string>172             </string>\r\n  <string>177             </string>\r\n " +
            " <string>187             </string>\r\n  <string>209             </string>\r\n  <stri" +
            "ng>249             </string>\r\n  <string>268             </string>\r\n  <string>276" +
            "             </string>\r\n  <string>290             </string>\r\n  <string>291      " +
            "       </string>\r\n  <string>299             </string>\r\n  <string>373            " +
            " </string>\r\n  <string>377             </string>\r\n  <string>378             </str" +
            "ing>\r\n  <string>422             </string>\r\n  <string>441             </string>\r\n" +
            "  <string>457             </string>\r\n  <string>463             </string>\r\n  <str" +
            "ing>468             </string>\r\n  <string>477             </string>\r\n  <string>53" +
            "6             </string>\r\n  <string>626             </string>\r\n  <string>629     " +
            "        </string>\r\n  <string>658             </string>\r\n  <string>661           " +
            "  </string>\r\n  <string>662             </string>\r\n  <string>671             </st" +
            "ring>\r\n  <string>674             </string>\r\n  <string>675             </string>\r" +
            "\n  <string>692             </string>\r\n  <string>697             </string>\r\n  <st" +
            "ring>698             </string>\r\n  <string>724             </string>\r\n  <string>7" +
            "27             </string>\r\n  <string>728             </string>\r\n  <string>742    " +
            "         </string>\r\n  <string>755             </string>\r\n  <string>762          " +
            "   </string>\r\n  <string>773             </string>\r\n  <string>780             </s" +
            "tring>\r\n  <string>791             </string>\r\n  <string>797             </string>" +
            "\r\n  <string>823             </string>\r\n  <string>824             </string>\r\n  <s" +
            "tring>825             </string>\r\n  <string>838             </string>\r\n  <string>" +
            "840             </string>\r\n  <string>856             </string>\r\n  <string>859   " +
            "          </string>\r\n  <string>864             </string>\r\n  <string>865         " +
            "    </string>\r\n  <string>914             </string>\r\n  <string>921             </" +
            "string>\r\n  <string>927             </string>\r\n  <string>935             </string" +
            ">\r\n  <string>952             </string>\r\n  <string>955             </string>\r\n  <" +
            "string>978             </string>\r\n  <string>979             </string>\r\n  <string" +
            ">981             </string>\r\n  <string>997             </string>\r\n</ArrayOfString" +
            ">")]
        public global::System.Collections.Specialized.StringCollection AllSites {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AllSites"]));
            }
            set {
                this["AllSites"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("namosnt.*.log")]
        public string FileNameLike {
            get {
                return ((string)(this["FileNameLike"]));
            }
            set {
                this["FileNameLike"] = value;
            }
        }
    }
}
