//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSCS.WinApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\DayEnd.log")]
        public string filePath {
            get {
                return ((string)(this["filePath"]));
            }
            set {
                this["filePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string searchText {
            get {
                return ((string)(this["searchText"]));
            }
            set {
                this["searchText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>162         </string>\r\n  <string>929          </string>\r\n  <string>159    " +
            "    </string>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <s" +
            "tring>162         </string>\r\n  <string>929          </string>\r\n  <string>159    " +
            "    </string>\r\n  <string>848       </string>\r\n  <string>152    </string>\r\n  <str" +
            "ing>162         </string>\r\n  <string>929          </string>\r\n  <string>159      " +
            "  </string>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <str" +
            "ing>162         </string>\r\n  <string>929          </string>\r\n  <string>159      " +
            "  </string>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <str" +
            "ing>162         </string>\r\n  <string>929          </string>\r\n  <string>159      " +
            "  </string>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <str" +
            "ing>162         </string>\r\n  <string>929          </string>\r\n  <string>159      " +
            "  </string>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <str" +
            "ing />\r\n  <string>162         </string>\r\n  <string>929          </string>\r\n  <st" +
            "ring>159        </string>\r\n  <string>848       </string>\r\n  <string>152      </s" +
            "tring>\r\n  <string />\r\n  <string>162         </string>\r\n  <string>929          </" +
            "string>\r\n  <string>159        </string>\r\n  <string>848       </string>\r\n  <strin" +
            "g>152      </string>\r\n  <string />\r\n  <string>162         </string>\r\n  <string>9" +
            "29          </string>\r\n  <string>159        </string>\r\n  <string>848       </str" +
            "ing>\r\n  <string>152      </string>\r\n  <string />\r\n  <string>162         </string" +
            ">\r\n  <string>929          </string>\r\n  <string>159        </string>\r\n  <string>8" +
            "48       </string>\r\n  <string>152      </string>\r\n  <string />\r\n  <string>162   " +
            "      </string>\r\n  <string>929          </string>\r\n  <string>159        </string" +
            ">\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <string>162   " +
            "      </string>\r\n  <string>929          </string>\r\n  <string>159        </string" +
            ">\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <string>162   " +
            "      </string>\r\n  <string>929          </string>\r\n  <string>159        </string" +
            ">\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <string>162   " +
            "      </string>\r\n  <string>929          </string>\r\n  <string>159        </string" +
            ">\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <string />\r\n  " +
            "<string />\r\n  <string>162         </string>\r\n  <string>929          </string>\r\n " +
            " <string>159        </string>\r\n  <string>848       </string>\r\n  <string>152     " +
            " </string>\r\n  <string />\r\n  <string>162         </string>\r\n  <string>929        " +
            "  </string>\r\n  <string>159        </string>\r\n  <string>848       </string>\r\n  <s" +
            "tring>152      </string>\r\n  <string />\r\n  <string>162         </string>\r\n  <stri" +
            "ng>929          </string>\r\n  <string>159        </string>\r\n  <string>848       <" +
            "/string>\r\n  <string>152      </string>\r\n  <string />\r\n  <string>162         </st" +
            "ring>\r\n  <string>929          </string>\r\n  <string>159        </string>\r\n  <stri" +
            "ng>848       </string>\r\n  <string>152      </string>\r\n  <string />\r\n  <string>16" +
            "2         </string>\r\n  <string>929          </string>\r\n  <string>159        </st" +
            "ring>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <string />" +
            "\r\n  <string>162         </string>\r\n  <string>929          </string>\r\n  <string>1" +
            "59        </string>\r\n  <string>848       </string>\r\n  <string>152      </string>" +
            "\r\n  <string />\r\n  <string>162         </string>\r\n  <string>929          </string" +
            ">\r\n  <string>159        </string>\r\n  <string>848       </string>\r\n  <string>152 " +
            "     </string>\r\n  <string />\r\n  <string>162         </string>\r\n  <string>929    " +
            "      </string>\r\n  <string>159        </string>\r\n  <string>848       </string>\r\n" +
            "  <string>152      </string>\r\n  <string />\r\n  <string>162         </string>\r\n  <" +
            "string>929          </string>\r\n  <string>159        </string>\r\n  <string>848    " +
            "   </string>\r\n  <string>152      </string>\r\n  <string />\r\n  <string>162         " +
            "</string>\r\n  <string>929          </string>\r\n  <string>159        </string>\r\n  <" +
            "string>848       </string>\r\n  <string>152      </string>\r\n  <string />\r\n  <strin" +
            "g>162         </string>\r\n  <string>929          </string>\r\n  <string>159        " +
            "</string>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <strin" +
            "g>162         </string>\r\n  <string>929          </string>\r\n  <string>159        " +
            "</string>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <strin" +
            "g>162         </string>\r\n  <string>929          </string>\r\n  <string>159        " +
            "</string>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <strin" +
            "g>162         </string>\r\n  <string>929          </string>\r\n  <string>159        " +
            "</string>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <strin" +
            "g />\r\n  <string>162         </string>\r\n  <string>929          </string>\r\n  <stri" +
            "ng>159        </string>\r\n  <string>848       </string>\r\n  <string>152      </str" +
            "ing>\r\n  <string />\r\n  <string>162         </string>\r\n  <string>929          </st" +
            "ring>\r\n  <string>159        </string>\r\n  <string>848       </string>\r\n  <string>" +
            "152      </string>\r\n  <string />\r\n  <string>162         </string>\r\n  <string>929" +
            "          </string>\r\n  <string>159        </string>\r\n  <string>848       </strin" +
            "g>\r\n  <string>152      </string>\r\n  <string />\r\n  <string>162         </string>\r" +
            "\n  <string>929          </string>\r\n  <string>159        </string>\r\n  <string>848" +
            "       </string>\r\n  <string>152      </string>\r\n  <string />\r\n  <string>162     " +
            "    </string>\r\n  <string>929          </string>\r\n  <string>159        </string>\r" +
            "\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <string />\r\n  <s" +
            "tring>162         </string>\r\n  <string>929          </string>\r\n  <string>159    " +
            "    </string>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <s" +
            "tring />\r\n  <string>162         </string>\r\n  <string>929          </string>\r\n  <" +
            "string>159        </string>\r\n  <string>848       </string>\r\n  <string>152      <" +
            "/string>\r\n  <string />\r\n  <string>162         </string>\r\n  <string>929          " +
            "</string>\r\n  <string>159        </string>\r\n  <string>848       </string>\r\n  <str" +
            "ing>152      </string>\r\n  <string />\r\n  <string>162         </string>\r\n  <string" +
            ">929          </string>\r\n  <string>159        </string>\r\n  <string>848       </s" +
            "tring>\r\n  <string>152      </string>\r\n  <string />\r\n  <string>162         </stri" +
            "ng>\r\n  <string>929          </string>\r\n  <string>159        </string>\r\n  <string" +
            ">848       </string>\r\n  <string>152      </string>\r\n  <string />\r\n  <string>162 " +
            "        </string>\r\n  <string>929          </string>\r\n  <string>159        </stri" +
            "ng>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <string>162 " +
            "        </string>\r\n  <string>929          </string>\r\n  <string>159        </stri" +
            "ng>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <string>162 " +
            "        </string>\r\n  <string>929          </string>\r\n  <string>159        </stri" +
            "ng>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <string>162 " +
            "        </string>\r\n  <string>929          </string>\r\n  <string>159        </stri" +
            "ng>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <string />\r\n" +
            "  <string>162         </string>\r\n  <string>929          </string>\r\n  <string>159" +
            "        </string>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n" +
            "  <string />\r\n  <string>162         </string>\r\n  <string>929          </string>\r" +
            "\n  <string>159        </string>\r\n  <string>848       </string>\r\n  <string>152   " +
            "   </string>\r\n  <string />\r\n  <string>162         </string>\r\n  <string>929      " +
            "    </string>\r\n  <string>159        </string>\r\n  <string>848       </string>\r\n  " +
            "<string>152      </string>\r\n  <string />\r\n  <string>162         </string>\r\n  <st" +
            "ring>929          </string>\r\n  <string>159        </string>\r\n  <string>848      " +
            " </string>\r\n  <string>152      </string>\r\n  <string />\r\n  <string>162         </" +
            "string>\r\n  <string>929          </string>\r\n  <string>159        </string>\r\n  <st" +
            "ring>848       </string>\r\n  <string>152      </string>\r\n  <string />\r\n  <string>" +
            "162         </string>\r\n  <string>929          </string>\r\n  <string>159        </" +
            "string>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <string " +
            "/>\r\n  <string>162         </string>\r\n  <string>929          </string>\r\n  <string" +
            ">159        </string>\r\n  <string>848       </string>\r\n  <string>152      </strin" +
            "g>\r\n  <string />\r\n  <string>162         </string>\r\n  <string>929          </stri" +
            "ng>\r\n  <string>159        </string>\r\n  <string>848       </string>\r\n  <string>15" +
            "2      </string>\r\n  <string />\r\n  <string>162         </string>\r\n  <string>929  " +
            "        </string>\r\n  <string>159        </string>\r\n  <string>848       </string>" +
            "\r\n  <string>152      </string>\r\n  <string />\r\n  <string>162         </string>\r\n " +
            " <string>929          </string>\r\n  <string>159        </string>\r\n  <string>848  " +
            "     </string>\r\n  <string>152      </string>\r\n  <string />\r\n  <string>162       " +
            "  </string>\r\n  <string>929          </string>\r\n  <string>159        </string>\r\n " +
            " <string>848       </string>\r\n  <string>152      </string>\r\n  <string>162       " +
            "  </string>\r\n  <string>929          </string>\r\n  <string>159        </string>\r\n " +
            " <string>848       </string>\r\n  <string>152      </string>\r\n  <string>162       " +
            "  </string>\r\n  <string>929          </string>\r\n  <string>159        </string>\r\n " +
            " <string>848       </string>\r\n  <string>152      </string>\r\n  <string>162       " +
            "  </string>\r\n  <string>929          </string>\r\n  <string>159        </string>\r\n " +
            " <string>848       </string>\r\n  <string>152      </string>\r\n  <string />\r\n  <str" +
            "ing>162         </string>\r\n  <string>929          </string>\r\n  <string>159      " +
            "  </string>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <str" +
            "ing />\r\n  <string>162         </string>\r\n  <string>929          </string>\r\n  <st" +
            "ring>159        </string>\r\n  <string>848       </string>\r\n  <string>152      </s" +
            "tring>\r\n  <string />\r\n  <string>162         </string>\r\n  <string>929          </" +
            "string>\r\n  <string>159        </string>\r\n  <string>848       </string>\r\n  <strin" +
            "g>152      </string>\r\n  <string />\r\n  <string>162         </string>\r\n  <string>9" +
            "29          </string>\r\n  <string>159        </string>\r\n  <string>848       </str" +
            "ing>\r\n  <string>152      </string>\r\n  <string />\r\n  <string>162         </string" +
            ">\r\n  <string>929          </string>\r\n  <string>159        </string>\r\n  <string>8" +
            "48       </string>\r\n  <string>152      </string>\r\n  <string />\r\n  <string>162   " +
            "      </string>\r\n  <string>929          </string>\r\n  <string>159        </string" +
            ">\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <string />\r\n  " +
            "<string>162         </string>\r\n  <string>929          </string>\r\n  <string>159  " +
            "      </string>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  " +
            "<string />\r\n  <string>162         </string>\r\n  <string>929          </string>\r\n " +
            " <string>159        </string>\r\n  <string>848       </string>\r\n  <string>152     " +
            " </string>\r\n  <string />\r\n  <string>162         </string>\r\n  <string>929        " +
            "  </string>\r\n  <string>159        </string>\r\n  <string>848       </string>\r\n  <s" +
            "tring>152      </string>\r\n  <string />\r\n  <string>162         </string>\r\n  <stri" +
            "ng>929          </string>\r\n  <string>159        </string>\r\n  <string>848       <" +
            "/string>\r\n  <string>152      </string>\r\n  <string />\r\n  <string>162         </st" +
            "ring>\r\n  <string>929          </string>\r\n  <string>159        </string>\r\n  <stri" +
            "ng>848       </string>\r\n  <string>152      </string>\r\n  <string>162         </st" +
            "ring>\r\n  <string>929          </string>\r\n  <string>159        </string>\r\n  <stri" +
            "ng>848       </string>\r\n  <string>152      </string>\r\n  <string>162         </st" +
            "ring>\r\n  <string>929          </string>\r\n  <string>159        </string>\r\n  <stri" +
            "ng>848       </string>\r\n  <string>152      </string>\r\n  <string>162         </st" +
            "ring>\r\n  <string>929          </string>\r\n  <string>159        </string>\r\n  <stri" +
            "ng>848       </string>\r\n  <string>152      </string>\r\n  <string />\r\n  <string>16" +
            "2         </string>\r\n  <string>929          </string>\r\n  <string>159        </st" +
            "ring>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <string />" +
            "\r\n  <string>162         </string>\r\n  <string>929          </string>\r\n  <string>1" +
            "59        </string>\r\n  <string>848       </string>\r\n  <string>152      </string>" +
            "\r\n  <string />\r\n  <string>162         </string>\r\n  <string>929          </string" +
            ">\r\n  <string>159        </string>\r\n  <string>848       </string>\r\n  <string>152 " +
            "     </string>\r\n  <string />\r\n  <string>162         </string>\r\n  <string>929    " +
            "      </string>\r\n  <string>159        </string>\r\n  <string>848       </string>\r\n" +
            "  <string>152      </string>\r\n  <string />\r\n  <string>162         </string>\r\n  <" +
            "string>929          </string>\r\n  <string>159        </string>\r\n  <string>848    " +
            "   </string>\r\n  <string>152      </string>\r\n  <string />\r\n  <string>162         " +
            "</string>\r\n  <string>929          </string>\r\n  <string>159        </string>\r\n  <" +
            "string>848       </string>\r\n  <string>152      </string>\r\n  <string />\r\n  <strin" +
            "g>162         </string>\r\n  <string>929          </string>\r\n  <string>159        " +
            "</string>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <strin" +
            "g>162         </string>\r\n  <string>929          </string>\r\n  <string>159        " +
            "</string>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <strin" +
            "g>162         </string>\r\n  <string>929          </string>\r\n  <string>159        " +
            "</string>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <strin" +
            "g>162         </string>\r\n  <string>929          </string>\r\n  <string>159        " +
            "</string>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <strin" +
            "g>162         </string>\r\n  <string>929          </string>\r\n  <string>159        " +
            "</string>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <strin" +
            "g>162         </string>\r\n  <string>929          </string>\r\n  <string>159        " +
            "</string>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <strin" +
            "g>162         </string>\r\n  <string>929          </string>\r\n  <string>159        " +
            "</string>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <strin" +
            "g>162         </string>\r\n  <string>929          </string>\r\n  <string>159        " +
            "</string>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <strin" +
            "g>162         </string>\r\n  <string>929          </string>\r\n  <string>159        " +
            "</string>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <strin" +
            "g>162         </string>\r\n  <string>929          </string>\r\n  <string>159        " +
            "</string>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <strin" +
            "g>162         </string>\r\n  <string>929          </string>\r\n  <string>159        " +
            "</string>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n  <strin" +
            "g>162         </string>\r\n  <string>929          </string>\r\n  <string>159        " +
            "</string>\r\n  <string>848       </string>\r\n  <string>152      </string>\r\n</ArrayO" +
            "fString>")]
        public global::System.Collections.Specialized.StringCollection AllSites {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AllSites"]));
            }
            set {
                this["AllSites"] = value;
            }
        }
    }
}
